### ISSUE TITLE
Cloned the files; now what?

### ISSUE THREAD

**Issue by kvaml** [hyphz/fr8x-editor#3]
I am new to the factor language. I've installed factor and it is working. I have cloned the repository. Now what should I do next??

Simply running factor in the fr8x-editor directory (and adding the missing Ubuntu packages) did the trick. 

cd /path/to/fr8x-editor
/path/to/factor

So you have nothing to fix. I thought this "issue" might be helpful for others. I had no idea what to do and tried running some of the factor programs as arguments to the factor language.

I am excited to use this software. Thanks for creating it.

**Comment by kvaml** [comment]
So that was just the factor browser starting up. I am still at a loss for how to run any of your factor programs.

**Comment by mrjbq7** [comment]
You can probably run it two easy ways...

1) from your Factor browser started in the fr8x-editor directory:

“fr8x-ui” run

2) from the command line in that same directory:

/path/to/factor -run=fr8x-ui

**Comment by kvaml** [comment]
I'm sorry, but I am still lost. Here's some info from my terminal window:

fr8x-editor$ ls -alrt
total 64
drwxr-xr-x 5 lkvam lkvam 4096 Jul 29 21:23 ..
-rw-r--r-- 1 lkvam lkvam  145 Jul 29 21:23 README.md
-rw-r--r-- 1 lkvam lkvam   77 Jul 29 21:23 .gitignore
-rw-r--r-- 1 lkvam lkvam   60 Jul 29 21:23 README.txt
drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-ui-gtk
drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-ui
drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-data-format-syntax
drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-data
drwxr-xr-x 7 lkvam lkvam 4096 Jul 29 21:23 .
drwxr-xr-x 8 lkvam lkvam 4096 Jul 29 21:23 .git

fr8x-editor$ cat README.*
fr8x-editor
===========

A PC based editor for data files from the Roland FR-8x V-Accordion.

See wiki for attempts at understanding the format.
The 'work' directory is for your own personal vocabularies.

--------------------------------------------------------

fr8x-editor$ ~/Downloads/factor/factor -run=fr8x-ui
Vocabulary does not exist
name "fr8x-ui"
(U) Quotation: [ c-to-factor => ]
    Word: c-to-factor
(U) Quotation: [ [ (get-catchstack) push ] dip call => (get-catchstack) pop* ]
(O) Word: command-line-startup
(O) Word: run
(O) Word: load-vocab
(O) Word: no-vocab
(O) Method: M\ object throw
(U) Quotation: [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]

---


So I have left out some important step. Sorry to be a nuisance. I just bought an FR8x and am
quite excited at playing it. This software looks like it will be of great assistance.

**Comment by mrjbq7** [comment]
I guess the current directory is not added by default as a “factor root” to look for source code. 

A suggestion:

Make a “~/.factor-roots” file that has a single line:

/path/to/fr8x-editor

And then you can run (from anywhere):

/path/to/factor -run=fr8x-ui

Try that!

I haven’t actually run this software myself, I just like to see Factor code!

**Comment by hyphz** [comment]
I’m really sorry to disappoint you but this isn’t a completed editor. The UI is not complete at all because I couldn’t get on with Factor’s UI library. You can use the data library to manipulate ST8 files from the Factor REPL if you wish. 

Roland now makes an official FR8x editor so I suggest using that instead. While you are on their site don’t forget to grab the firmware update and free expansion packs. Happy squeezing :)

**Comment by kvaml** [comment]
Thank you very much!! 

I am now executing the fr8x-editor code. Hopefully the author offers a hand, though I suppose
it will do me good to study some factor code.

The results follow. I will start combing through the source this evening.


$ echo $(pwd) > ~/.factor-roots

$ cat ~/.factor-roots 
/home/lkvam/Hardware/Roland8x/fr8x-editor

$ /home/lkvam/Downloads/factor/factor -run=fr8x-ui
/home/lkvam/Hardware/Roland8x/fr8x-editor/fr8x-ui/fr8x-ui.factor

3: USING: accessors assocs fry kernel locals make math math.parser
7: ui.gadgets.menus ui.gadgets.tracks namespaces fr8x-data 
                                                          ^
/home/lkvam/Hardware/Roland8x/fr8x-editor/fr8x-data/fr8x-data.factor

3: USING: accessors arrays assocs bitstreams byte-arrays
4: fr8x-data-format-syntax fry io io.directories
                          ^
/home/lkvam/Hardware/Roland8x/fr8x-editor/fr8x-data-format-syntax/fr8x-data-format-syntax.factor

36:       [ "unpack-" prepend create-in ]
                                       ^
No word named “create-in” found in current vocabulary search path
(U) Quotation: [ c-to-factor => ]
    Word: c-to-factor
(U) Quotation: [ [ (get-catchstack) push ] dip call => (get-catchstack) pop* ]
(O) Word: command-line-startup
(O) Word: run
(O) Word: load-vocab
(O) Method: M\ vocab (require)
(O) Word: load-source
(O) Word: parse-file
(O) Word: parse-stream
(O) Word: parse-fresh
(O) Word: (parse-lines)
(O) Word: (parse-until)
(O) Word: parse-until-step
(O) Word: execute-parsing
(O) Word: POSTPONE: USING:
(O) Word: use-vocab
(O) Word: load-vocab
(O) Method: M\ vocab (require)
(O) Word: load-source
(O) Word: parse-file
(O) Word: parse-stream
(O) Word: parse-fresh
(O) Word: (parse-lines)
(O) Word: (parse-until)
(O) Word: parse-until-step
(O) Word: execute-parsing
(O) Word: POSTPONE: USING:
(O) Word: use-vocab
(O) Word: load-vocab
(O) Method: M\ vocab (require)
(O) Word: load-source
(O) Word: parse-file
(O) Word: parse-stream
(O) Word: parse-fresh
(O) Word: (parse-lines)
(O) Word: (parse-until)
(O) Word: parse-until-step
(O) Word: execute-parsing
(O) Word: POSTPONE: SYNTAX:
(O) Word: parse-definition
(O) Word: (parse-until)
(O) Word: parse-until-step
(O) Word: execute-parsing
(O) Word: POSTPONE: [
(O) Method: M\ POSTPONE: f parse-quotation
(O) Word: (parse-until)
(O) Word: parse-until-step
(O) Word: no-word
(O) Word: throw-restarts
(O) Method: M\ object throw
(U) Quotation: [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]



On Tue, 2019-07-30 at 09:52 -0700, John Benediktsson wrote:
> I guess the current directory is not added by default as a “factor root” to look for source
> code. 
> 
> A suggestion:
> 
> Make a “~/.factor-roots” file that has a single line:
> 
> /path/to/fr8x-editor
> 
> And then you can run (from anywhere):
> 
> /path/to/factor -run=fr8x-ui
> 
> Try that!
> 
> I haven’t actually run this software myself, I just like to see Factor code!
> 
> 
> > On Jul 30, 2019, at 9:46 AM, kvaml <notifications@github.com> wrote:
> > 
> > I'm sorry, but I am still lost. Here's some info from my terminal window:
> > 
> > fr8x-editor$ ls -alrt
> > total 64
> > drwxr-xr-x 5 lkvam lkvam 4096 Jul 29 21:23 ..
> > -rw-r--r-- 1 lkvam lkvam 145 Jul 29 21:23 README.md
> > -rw-r--r-- 1 lkvam lkvam 77 Jul 29 21:23 .gitignore
> > -rw-r--r-- 1 lkvam lkvam 60 Jul 29 21:23 README.txt
> > drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-ui-gtk
> > drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-ui
> > drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-data-format-syntax
> > drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-data
> > drwxr-xr-x 7 lkvam lkvam 4096 Jul 29 21:23 .
> > drwxr-xr-x 8 lkvam lkvam 4096 Jul 29 21:23 .git
> > 
> > fr8x-editor$ cat README.*
> > fr8x-editor
> > ===========
> > 
> > A PC based editor for data files from the Roland FR-8x V-Accordion.
> > 
> > See wiki for attempts at understanding the format.
> > The 'work' directory is for your own personal vocabularies.
> > 
> > --------------------------------------------------------
> > 
> > fr8x-editor$ ~/Downloads/factor/factor -run=fr8x-ui
> > Vocabulary does not exist
> > name "fr8x-ui"
> > (U) Quotation: [ c-to-factor => ]
> > Word: c-to-factor
> > (U) Quotation: [ [ (get-catchstack) push ] dip call => (get-catchstack) pop* ]
> > (O) Word: command-line-startup
> > (O) Word: run
> > (O) Word: load-vocab
> > (O) Word: no-vocab
> > (O) Method: M\ object throw
> > (U) Quotation: [
> > OBJ-CURRENT-THREAD special-object error-thread set-global
> > current-continuation => error-continuation set-global
> > [ original-error set-global ] [ rethrow ] bi
> > ]
> > 
> > ---
> > 
> > 
> > So I have left out some important step. Sorry to be a nuisance. I just bought an FR8x and
> > am
> > quite excited at playing it. This software looks like it will be of great assistance.
> > 
> > 
> > 
> > On Tue, 2019-07-30 at 07:20 -0700, John Benediktsson wrote:
> > > You can probably run it two easy ways...
> > > 
> > > 1) from your Factor browser started in the fr8x-editor directory:
> > > 
> > > “fr8x-ui” run
> > > 
> > > 2) from the command line in that same directory:
> > > 
> > > /path/to/factor -run=fr8x-ui
> > > 
> > > 
> > > 
> > > 
> > > > On Jul 29, 2019, at 7:01 PM, kvaml <notifications@github.com> wrote:
> > > > 
> > > > So that was just the factor browser starting up. I am still at a loss for how to run
> > > > any of
> > > > your factor programs.
> > > > 
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly, view it on GitHub, or mute the thread.
> > > 
> > > 
> > > -- 
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/hyphz/fr8x-editor/issues/3#issuecomment-516440561
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/hyphz/fr8x-editor/issues/3#issuecomment-516503109
-- 
Lloyd Kvam
5 Foliage View
Lebanon, NH 03766
802-448-0836

**Comment by kvaml** [comment]
On Tue, 2019-07-30 at 10:51 -0700, Mark Green wrote:
> I’m really sorry to disappoint you but this isn’t a completed editor. The UI is not complete
> at all because I couldn’t get on with Factor’s UI library. You can use the data library to
> manipulate ST8 files from the Factor REPL if you wish. 

My main goal is to pull data from the files to document and cross-reference the settings. I am
not looking for a GUI other than as an assist in finding my way around within the software.

Can you suggest one factor command line that would work?


> Roland now makes an official FR8x editor so I suggest using that instead. While you are on
> their site don’t forget to grab the firmware update and free expansion packs. Happy squeezing
> :) 

The Roland editor works nicely one User Program or Set register at a time. I'm looking to
create some documentation that lets me find my way around: i.e. which user programs use an alto
sax?

You have done the heavy lifting to parse the files and extract the data. I'm looking to
organize the data. If I need to learn factor along the way, I'll do so. I'm happy to post any
useful stuff back to your github project.

I'm not promising any great results in a short time frame, but I think I need a better overview
if I'm going to be successful with this instrument.

> 
> > On 30 Jul 2019, at 17:52, John Benediktsson <notifications@github.com> wrote:
> > 
> > I guess the current directory is not added by default as a “factor root” to look for source
> > code. 
> > 
> > A suggestion:
> > 
> > Make a “~/.factor-roots” file that has a single line:
> > 
> > /path/to/fr8x-editor
> > 
> > And then you can run (from anywhere):
> > 
> > /path/to/factor -run=fr8x-ui
> > 
> > Try that!
> > 
> > I haven’t actually run this software myself, I just like to see Factor code!
> > 
> > 
> > > On Jul 30, 2019, at 9:46 AM, kvaml <notifications@github.com> wrote:
> > > 
> > > I'm sorry, but I am still lost. Here's some info from my terminal window:
> > > 
> > > fr8x-editor$ ls -alrt
> > > total 64
> > > drwxr-xr-x 5 lkvam lkvam 4096 Jul 29 21:23 ..
> > > -rw-r--r-- 1 lkvam lkvam 145 Jul 29 21:23 README.md
> > > -rw-r--r-- 1 lkvam lkvam 77 Jul 29 21:23 .gitignore
> > > -rw-r--r-- 1 lkvam lkvam 60 Jul 29 21:23 README.txt
> > > drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-ui-gtk
> > > drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-ui
> > > drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-data-format-syntax
> > > drwxr-xr-x 2 lkvam lkvam 4096 Jul 29 21:23 fr8x-data
> > > drwxr-xr-x 7 lkvam lkvam 4096 Jul 29 21:23 .
> > > drwxr-xr-x 8 lkvam lkvam 4096 Jul 29 21:23 .git
> > > 
> > > fr8x-editor$ cat README.*
> > > fr8x-editor
> > > ===========
> > > 
> > > A PC based editor for data files from the Roland FR-8x V-Accordion.
> > > 
> > > See wiki for attempts at understanding the format.
> > > The 'work' directory is for your own personal vocabularies.
> > > 
> > > --------------------------------------------------------
> > > 
> > > fr8x-editor$ ~/Downloads/factor/factor -run=fr8x-ui
> > > Vocabulary does not exist
> > > name "fr8x-ui"
> > > (U) Quotation: [ c-to-factor => ]
> > > Word: c-to-factor
> > > (U) Quotation: [ [ (get-catchstack) push ] dip call => (get-catchstack) pop* ]
> > > (O) Word: command-line-startup
> > > (O) Word: run
> > > (O) Word: load-vocab
> > > (O) Word: no-vocab
> > > (O) Method: M\ object throw
> > > (U) Quotation: [
> > > OBJ-CURRENT-THREAD special-object error-thread set-global
> > > current-continuation => error-continuation set-global
> > > [ original-error set-global ] [ rethrow ] bi
> > > ]
> > > 
> > > ---
> > > 
> > > 
> > > So I have left out some important step. Sorry to be a nuisance. I just bought an FR8x and
> > > am
> > > quite excited at playing it. This software looks like it will be of great assistance.
> > > 
> > > 
> > > 
> > > On Tue, 2019-07-30 at 07:20 -0700, John Benediktsson wrote:
> > > > You can probably run it two easy ways...
> > > > 
> > > > 1) from your Factor browser started in the fr8x-editor directory:
> > > > 
> > > > “fr8x-ui” run
> > > > 
> > > > 2) from the command line in that same directory:
> > > > 
> > > > /path/to/factor -run=fr8x-ui
> > > > 
> > > > 
> > > > 
> > > > 
> > > > > On Jul 29, 2019, at 7:01 PM, kvaml <notifications@github.com> wrote:
> > > > > 
> > > > > So that was just the factor browser starting up. I am still at a loss for how to run
> > > > > any of
> > > > > your factor programs.
> > > > > 
> > > > > —
> > > > > You are receiving this because you are subscribed to this thread.
> > > > > Reply to this email directly, view it on GitHub, or mute the thread.
> > > > 
> > > > 
> > > > -- 
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/hyphz/fr8x-editor/issues/3#issuecomment-516440561
> > > 
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub, or mute the thread.
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/hyphz/fr8x-editor/issues/3#issuecomment-516524195
-- 
Lloyd Kvam
5 Foliage View
Lebanon, NH 03766
802-448-0836

**Comment by mrjbq7** [comment]
Looks like a little bit-rot from some updates in the last couple Factor releases. 

I’d be happy to fix up the code to work with Factor 0.98 release (and 0.99-dev) but won’t have time until Thursday. 

create-in probably got renamed to create-word-in:

https://docs.factorcode.org/content/word-create-word-in,parser.html

**Comment by MarkRdgOx** [comment]
Ok, @mrjbq7 was right above. I've fixed the _create-in_ reference.

From the Factor REPL:

1. Add the vocab root `"path\to\fr8x-editor" add-vocab-root` . Note, this is case sensitive and is not validated.
2. Load the data library `USING: fr8x-data ;`
3. Load a set file. There isn't one in the repository because of potential copyright issues but you can export one from your V-Accordion or download one from Roland or another user site. Then, `"setfile.st8" load-set-file` . You will see a complex object on the stack, this is the decoded set.
4. You will now need to refer to the wiki for the chunks of the set file. IN your case, for example, if you want to find alto sax that would be in a orchestra right hand register which is in the "O_R" chunk. So `dup "O_R" get-chunk` will put the TR list on the stack (while leaving the full set file below it in case you want it later)
5. This is a list of `orData` objects. You can get data from them using field functions and use list combinators to apply them to the whole list. For example you can get all the names with `[ custom-name>> ] map` (again throw a `dup` in at the start if you want to keep the list around) 
6. The patch used in each one is stored only as three numbers in the set file, in fields patch-00, patch-cc32 and patch-pc . The corresponding names are listed in the `midivoices.txt` and `midireeds.txt` files. Look in this and you will see Alto Sax is `0 0 122`. So you can search the list for this with `[ [ patch-cc00>> 0 = ] [ patch-cc32>> 0 = ] [ patch-pc>> 122 = ] tri and and ] filter` (@mrjbq7 can probably tell you a nicer syntax for this!)

**Comment by kvaml** [comment]
Thanks. This WORKED!

So I can parse a set and pull off some data. You have already provided documentation for the
Roland files as well as translation tables to provide instrument names.

Knowing I can execute one of your functions successfully means I can start making some
progress. I still have a lot to learn about factor.

Hopefully I am done with being a bother.

On Tue, 2019-07-30 at 14:54 -0700, Mark Green wrote:
> Ok, @mrjbq7 was right above. I've fixed the _create-in_ reference.
> 
> From the Factor REPL:
> 
> 1. Add the vocab root `"path\to\fr8x-editor" add-vocab-root` . Note, this is case sensitive
> and is not validated.
> 2. Load the data library `USING: fr8x-data ;`
> 3. Load a set file. There isn't one in the repository because of potential copyright issues
> but you can export one from your V-Accordion or download one from Roland or another user
> site. Then, `"setfile.st8" load-set-file` . You will see a complex object on the stack, this
> is the decoded set.
> 4. You will now need to refer to the wiki for the chunks of the set file. IN your case, for
> example, if you want to find alto sax that would be in a orchestra right hand register which
> is in the "O_R" chunk. So `dup "O_R" get-chunk` will put the TR list on the stack (while
> leaving the full set file below it in case you want it later)
> 5. This is a list of `orData` objects. You can get data from them using field functions and
> use list combinators to apply them to the whole list. For example you can get all the names
> with `[ custom-name>> map ]` (again throw a `dup` in at the start if you want to keep the
> list around) 
> 6. The patch used in each one is stored only as three numbers in the set file, in fields
> patch-00, patch-cc32 and patch-pc . The corresponding names are listed in the
> `midivoices.txt` and `midireeds.txt` files. Look in this and you will see Alto Sax is `0 0
> 122`. So you can search the list for this with `[ [ patch-cc00>> 0 = ] [ patch-cc32>> 0 = ] [
> patch-pc>> 122 = ] tri and and ] filter` (@mrjbq7 can probably tell you a nicer syntax for
> this!)
> 
> 
-- 
Lloyd Kvam
5 Foliage View
Lebanon, NH 03766
802-448-0836

**Comment by mrjbq7** [comment]
I always like feedback on what’s working and what isn’t with Factor. Feel free to open issues or ask questions.

http://github.com/factor/factor
